name: Always Fail Action

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  push:
    branches: [main]

jobs:
  failing-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Print environment info
      run: |
        echo "This action is designed to always fail"
        echo "Runner OS: ${{ runner.os }}"
        echo "Event name: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref }}"
        
    - name: Install dependencies (fake)
      run: |
        echo "Installing fake dependencies..."
        sleep 2
        echo "Dependencies installed successfully"
        
    - name: Run tests (always fails)
      run: |
        echo "Running tests..."
        echo "Test 1: PASS"
        echo "Test 2: PASS"
        echo "Test 3: FAIL - Critical error detected"
        echo "ERROR: Test suite failed with exit code 1"
        exit 1
        
    - name: This step will never run
      run: |
        echo "This step should never execute because the previous step failed"
